# -*- coding: utf-8 -*-
"""ocr_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mf_xJPG0J13oettlTsf5BIkC7YWCmD9_
"""

!pip install easyocr opencv-python-headless matplotlib

from google.colab import drive
drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/AI-OCR dataset"

import os
print(os.listdir('/content/drive/MyDrive'))

import os
li_images = []
for file in os.listdir(folder_path):
  if file.endswith(('.jpg', '.png', '.jpeg')):
    li_images.append(os.path.join( folder_path, file))

print(li_images[:10])

import cv2
import matplotlib.pyplot as plt

img_path = li_images[0]

image_bgr = cv2.imread(img_path)
image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

plt.imshow(image_rgb)
plt.axis('off')
plt.show()

import easyocr
reader = easyocr.Reader(['en'], gpu = True)
results = reader.readtext(img_path)
for bbox, text, confidence in results:
  print(f"{text} | {confidence:.2f}")

import cv2
image_bgr = cv2.imread(img_path)

image_gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
image_blur = cv2.GaussianBlur(image_gray, (5,5), 0)
image_thresholded = cv2.threshold(image_blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

plt.imshow(image_thresholded, cmap='gray')
plt.axis('off')
plt.show()

results = reader.readtext(image_thresholded)
for bbox, text, confidence in results:
  print(f"{text} | {confidence:.2f}")

import cv2
sample_images = li_images[:5]
for img_path in sample_images:
  print('\n-------------------------------------')
  print("Image:", img_path)

  image_bgr = cv2.imread(img_path)

  raw_results = reader.readtext(image_bgr)
  print("\nRAW:")
  for bbox, text, confidence in raw_results:
    print(f"{text} | {confidence:.2f}")


  image_gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
  print("\nGRAYSCALE:")
  gray_results = reader.readtext(image_gray)
  for bbox, text, confidence in gray_results:
    print(f"{text} | {confidence:.2f}")

  image_blur = cv2.GaussianBlur(image_gray, (3,3), 0)
  print("\nBLUR:")
  blur_results = reader.readtext(image_blur)
  for bbox, text, confidence in blur_results:
    print(f"{text} | {confidence:.2f}")

  image_thresholded = cv2.threshold(image_blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
  print("\nTHRESHOLD:")
  thresh_results = reader.readtext(image_thresholded)
  for bbox, text, confidence in thresh_results:
    print(f"{text} | {confidence:.2f}")

import numpy as np

def correct_skew(image):
    coords = np.column_stack(np.where(image > 0))
    if len(coords) < 10:
        return image
    angle = cv2.minAreaRect(coords)[-1]
    if angle < -45:
        angle = -(90 + angle)
    else:
        angle = -angle
    (h, w) = image.shape[:2]
    M = cv2.getRotationMatrix2D((w//2, h//2), angle, 1.0)
    return cv2.warpAffine(image, M, (w, h), flags=cv2.INTER_CUBIC, borderMode=cv2.BORDER_REPLICATE)

def fix_contrast(image):
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    return clahe.apply(image)

def preprocess_image(img_bgr):
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    contrast = fix_contrast(gray)
    blur = cv2.GaussianBlur(contrast, (3,3), 0)
    thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
    deskewed = correct_skew(thresh)
    return deskewed

def avg_confidence(results):
  if len(results)==0:
    return 0
  return sum([conf for _, _, conf in results])/len(results)

def impword_score(results):
  important_words = ["total", "amount", "date"]
  text_list = [text.lower() for _, text, _ in results]
  score = 0
  for word in important_words:
    if any(word in t for t in text_list):
      score += 1
  return score

def best_ocr(image_bgr):
  results_dict = {}
  results_dict['raw'] = reader.readtext(image_bgr)

  image_gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
  results_dict['gray'] = reader.readtext(image_gray)

  image_blur = cv2.GaussianBlur(image_gray, (3,3), 0)
  results_dict['blur'] = reader.readtext(image_blur)

  image_thresh = cv2.threshold(image_blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
  results_dict['thresh'] = reader.readtext(image_thresh)

  image_preprocessed = preprocess_image(image_bgr)  # skew + contrast
  results_dict['preprocessed'] = reader.readtext(image_preprocessed)




  best_score = -1
  best_method = None
  best_result = None
  for method, results in results_dict.items():
    avg_conf = avg_confidence(results)
    imp_word_score = impword_score(results)
    total_score = avg_conf + imp_word_score
    print(f"{method}: {total_score:.2f}")
    if total_score > best_score:
      best_score = total_score
      best_method = method
      best_result = results
  return best_method, best_result


img = cv2.imread(li_images[0])

method,result = best_ocr(img)
print(f"Best method: {method}")
for bbox, text, confidence in result:
  print(f"{text} | {confidence:.2f}")

all_results = []

for img_path in li_images[:5]:
  img = cv2.imread(img_path)
  method, result = best_ocr(img)

  all_results.append({"image": img_path, "method": method, "result": result})

def ocr_to_lines(ocr_result, y_threshold=15):
    ocr_result = sorted(ocr_result, key=lambda x: x[0][0][1])

    lines = []
    current_line = []
    current_y = None

    for bbox, text, conf in ocr_result:
        y = bbox[0][1]

        if current_y is None:
            current_y = y

        if abs(y - current_y) < y_threshold:
            current_line.append((text, conf))
        else:
            line_text = " ".join([t for t, _ in current_line])
            avg_conf = sum([c for _, c in current_line]) / len(current_line)
            lines.append((line_text, avg_conf))

            current_line = [(text, conf)]
            current_y = y

    if current_line:
        line_text = " ".join([t for t, _ in current_line])
        avg_conf = sum([c for _, c in current_line]) / len(current_line)
        lines.append((line_text, avg_conf))

    return lines

lines = ocr_to_lines(result)

for l in lines:
    print(l)

import re
from dateutil import parser as dateparser

def normalize_ocr_text(text):
    replacements = {'0':'O','1':'I','5':'S','8':'B','@':'A','|':'I'}
    result = text.upper()
    for wrong, right in replacements.items():
        result = result.replace(wrong, right)
    return result

def is_total_keyword(text):
    t = normalize_ocr_text(text)
    keywords = ['TOTAL','SUBTOTAL','SUB TOTAL','AMOUNT DUE','AMT DUE',
                'BALANCE DUE','GRAND TOTAL','NET AMOUNT','TOIAI','TOIAL']
    return any(k in t for k in keywords)

def is_skip_line(text):
    skip = ['change','cash','tender','paid','savings','you save',
            'discount','tax','gst','vat','purchase','includes']
    return any(k in text.lower() for k in skip)

def get_price_from_text(text, allow_whole_number=False):
    nums = re.findall(r'\$?\s*(\d{1,6}[.,]\d{2})\b', text)
    if nums:
        return round(float(nums[-1].replace(',','.')), 2)

    if allow_whole_number:
        whole = re.findall(r'\b(\d{2,4})\s*$', text.strip())
        if whole:
            val = float(whole[-1])
            if 1 < val < 10000:
                return round(val, 2)
    return None

def extract_date(lines):
    patterns = [
        r'\b\d{1,2}[\/\-\.]\d{1,2}[\/\-\.]\d{2,4}\b',
        r'\b\d{4}[\/\-\.]\d{1,2}[\/\-\.]\d{1,2}\b',
        r'\b\d{1,2}[\s\-]?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*[\s\-]?\d{2,4}\b',
        r'\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*[\s\.\-]\d{1,2}[\s\.\-,]\d{2,4}\b',
    ]
    best_date, best_conf = None, 0.0
    for text, conf in lines:
        for pattern in patterns:
            for match in re.finditer(pattern, text, re.IGNORECASE):
                raw = match.group().strip()

                if re.match(r'^\d{2}:\d{2}(:\d{2})?$', raw):
                    continue

                try:
                    parsed = dateparser.parse(raw, dayfirst=False)
                    if parsed and 1990 <= parsed.year <= 2030:
                        if conf > best_conf:
                            best_date = parsed.strftime('%Y-%m-%d')
                            best_conf = conf
                except:
                    continue
    return best_date, best_conf

def extract_total(lines, raw_ocr_result):
    candidates = []

    for i, (text, conf) in enumerate(lines):
        if is_total_keyword(text) and not is_skip_line(text):
            price = get_price_from_text(text, allow_whole_number=False)
            if price and price > 0:
                score = 3 if 'grand' in text.lower() else 2
                candidates.append((price, score, conf))

    for i, (text, conf) in enumerate(lines[:-1]):
        if is_total_keyword(text) and not is_skip_line(text):
            next_text, next_conf = lines[i+1]
            price = get_price_from_text(next_text, allow_whole_number=False)
            if price and price > 0:
                candidates.append((price, 2, (conf + next_conf) / 2))

    if not candidates:
        sorted_raw = sorted(raw_ocr_result, key=lambda x: x[0][0][1])
        for i, (bbox, text, conf) in enumerate(sorted_raw):
            if is_total_keyword(text) and not is_skip_line(text):
                y_center = (bbox[0][1] + bbox[2][1]) / 2
                for j, (bbox2, text2, conf2) in enumerate(sorted_raw):
                    if i == j:
                        continue
                    y2 = (bbox2[0][1] + bbox2[2][1]) / 2
                    if abs(y_center - y2) < 25:
                        price = get_price_from_text(text2, allow_whole_number=False)
                        if price and price > 0:
                            candidates.append((price, 2, (conf + conf2) / 2))

    if not candidates:
        for i, (text, conf) in enumerate(lines):
            if is_total_keyword(text) and not is_skip_line(text):
                price = get_price_from_text(text, allow_whole_number=True)
                if price and price > 0:
                    candidates.append((price, 1, conf))

    if not candidates:
        return None, 0.0

    candidates.sort(key=lambda x: (x[1], x[0]), reverse=True)
    best_val, _, best_conf = candidates[0]
    return str(round(best_val, 2)), round(best_conf, 2)

def extract_store(lines):
    skip_words = ['gst','tax','invoice','bill','date','receipt','tel','phone',
                  'www','http','total','amount','thank','welcome','items','open',
                  'manager','always','low price','supercenter','hours','sdn','bhd']
    for text, conf in lines[:10]:
        if conf < 0.45:
            continue
        t = text.strip()
        if len(t) < 3:
            continue
        if any(w in t.lower() for w in skip_words):
            continue
        alpha_ratio = sum(c.isalpha() for c in t) / max(len(t), 1)
        if alpha_ratio < 0.4:
            continue
        ascii_ratio = sum(c.isascii() for c in t) / max(len(t), 1)
        if ascii_ratio < 0.6:
            continue
        return t, conf
    return None, 0.0

def clean_item_name(text):
    name = re.sub(r'\b\d{5,}\b', '', text)
    name = re.sub(r'\$?\s*\d+[.,]\d{2}', '', name)
    name = re.sub(r'\b\d+\s*[xX]\s*\d+\b', '', name)
    name = re.sub(r'\s+[FNTXB]\s*$', '', name)
    name = re.sub(r'\b\d+\b', '', name)
    name = re.sub(r'[^\w\s\-&\'/]', ' ', name)
    name = re.sub(r'\s{2,}', ' ', name).strip()
    return name

def extract_items(lines, total_str, raw_ocr_result):
    total_value = float(total_str) if total_str else None
    SKIP_KEYWORDS = ['total','subtotal','sub-total','tax','gst','vat','change',
                     'cash','discount','amount','balance','tender','credit',
                     'debit','visa','mastercard','savings','thank','welcome',
                     'items sold','purchase','qty item','rounded','includes']
    items = []
    seen_prices = set()

    for text, conf in lines:
        if conf < 0.3:
            continue
        t_lower = text.lower()
        if any(kw in t_lower for kw in SKIP_KEYWORDS):
            continue
        if not re.search(r'[A-Za-z]{2,}', text):
            continue

        nums = re.findall(r'\$?\s*(\d{1,4}[.,]\d{2})\b', text)
        if not nums:
            continue

        price_str = nums[-1].replace(',','.')
        price_val = round(float(price_str), 2)

        if price_val <= 0:
            continue
        if total_value and abs(price_val - total_value) < 0.02:
            continue
        if price_val in seen_prices:
            continue
        seen_prices.add(price_val)

        name = clean_item_name(text)
        if len(name) < 3:
            continue

        items.append({
            "name":       name,
            "price":      str(price_val),
            "confidence": round(conf, 2)
        })

    return items

def safe_extract(img_path):
    try:
        img = cv2.imread(img_path)
        if img is None:
            raise ValueError("Could not read image")
        if img.shape[0] < 50 or img.shape[1] < 50:
            raise ValueError("Image too small")
        method, result = best_ocr(img)
        if not result:
            raise ValueError("No text detected")
        lines = ocr_to_lines(result)
        return build_structured_output(img_path, lines, result)
    except Exception as e:
        return {
            "image": img_path,
            "error": str(e),
            "store_name":   {"value": None, "confidence": 0.0, "low_confidence": True},
            "date":         {"value": None, "confidence": 0.0, "low_confidence": True},
            "total_amount": {"value": None, "confidence": 0.0, "low_confidence": True},
            "items":        [],
            "ocr_quality":  0.0
        }

import json

test_images = li_images[:3]

for img_path in test_images:
    print("\n" + "="*60)
    print("Image:", img_path)

    img = cv2.imread(img_path)
    method, result = best_ocr(img)
    lines = ocr_to_lines(result)

    output = build_structured_output(img_path, lines, result)

    print("Store :", output['store_name']['value'], "| conf:", output['store_name']['confidence'])
    print("Date  :", output['date']['value'],       "| conf:", output['date']['confidence'])
    print("Total :", output['total_amount']['value'],"| conf:", output['total_amount']['confidence'])
    print(f"Items : ({len(output['items'])} found)")
    for it in output['items'][:5]:
        print(f"   {it['name']:<30} ${it['price']:<8} conf={it['confidence']}")
    print("OCR quality:", output['ocr_quality'])

def normalize_store_name(name):
    if not name:
        return "Unknown"
    # lowercase, strip punctuation, collapse spaces
    n = re.sub(r'[^a-z0-9 ]', '', name.lower())
    n = re.sub(r'\s+', ' ', n).strip()
    return n

def generate_financial_summary(all_outputs):
    total_spend = 0.0
    store_spend = {}
    valid_transactions = 0
    flagged_transactions = 0

    for r in all_outputs:
        if 'error' in r:
            flagged_transactions += 1
            continue

        t = r['total_amount']
        if t['value'] and not t['low_confidence']:
            val = float(t['value'])
            total_spend += val
            valid_transactions += 1
            raw_store = r['store_name']['value'] or 'Unknown'
            store = normalize_store_name(raw_store)  # ← normalized key
            store_spend[store] = round(store_spend.get(store, 0) + val, 2)
        else:
            flagged_transactions += 1

    return {
        "total_spend":                  round(total_spend, 2),
        "num_transactions":             len(all_outputs),
        "high_confidence_transactions": valid_transactions,
        "flagged_low_confidence":       flagged_transactions,
        "spend_per_store":              store_spend
    }

def validate_confidence(value, field_type, ocr_conf):
    if value is None:
        return 0.0

    bonus = 0.0

    if field_type == 'date':
        if re.match(r'\d{4}-\d{2}-\d{2}', str(value)):
            bonus = 0.1

    elif field_type == 'total':
        if re.match(r'^\d+\.\d{2}$', str(value)):
            bonus = 0.1
        if re.match(r'^\d+\.0$', str(value)):
            bonus = -0.15

    elif field_type == 'store':
        if value and sum(c.isalpha() for c in value) / max(len(value),1) > 0.7:
            bonus = 0.05

    return round(min(1.0, max(0.0, ocr_conf + bonus)), 2)

def build_structured_output(img_path, lines, ocr_results):
    store, s_conf = extract_store(lines)
    date,  d_conf = extract_date(lines)
    total, t_conf = extract_total(lines, ocr_results)
    items         = extract_items(lines, total, ocr_results)
    avg_ocr_conf  = sum(c for _,_,c in ocr_results) / max(len(ocr_results), 1)

    s_conf = validate_confidence(store, 'store', s_conf)
    d_conf = validate_confidence(date,  'date',  d_conf)
    t_conf = validate_confidence(total, 'total', t_conf)

    flag = lambda conf: bool(conf < 0.7)

    return {
        "image":        img_path,
        "store_name":   {"value": store,  "confidence": s_conf, "low_confidence": flag(s_conf)},
        "date":         {"value": date,   "confidence": d_conf, "low_confidence": flag(d_conf)},
        "total_amount": {"value": total,  "confidence": t_conf, "low_confidence": flag(t_conf)},
        "items":        items,
        "ocr_quality":  round(avg_ocr_conf, 2)
    }

def is_low_quality_result(output):
    fields_found = sum([
        output['store_name']['value'] is not None,
        output['date']['value'] is not None,
        output['total_amount']['value'] is not None,
    ])
    return fields_found == 0

import os, json

output_dir = '/content/drive/MyDrive/AI-OCR outputs'
os.makedirs(output_dir, exist_ok=True)

all_outputs = []
for img_path in li_images:
    print(f"Processing: {img_path}")
    output = safe_extract(img_path)
    all_outputs.append(output)

    fname = os.path.basename(img_path).rsplit('.',1)[0] + '.json'
    with open(os.path.join(output_dir, fname), 'w') as f:
        json.dump(output, f, indent=2, default=str)


summary = generate_financial_summary(all_outputs)
with open(os.path.join(output_dir, 'financial_summary.json'), 'w') as f:
    json.dump(summary, f, indent=2)

print("\n===== FINANCIAL SUMMARY =====")
print(json.dumps(summary, indent=2))

!nvidia-smi

for img_path in li_images[:4]:
    img = cv2.imread(img_path)
    method, result = best_ocr(img)
    lines = ocr_to_lines(result)
    output = build_structured_output(img_path, lines, result)
    print(img_path.split('/')[-1], "→ Store:", output['store_name']['value'])

lines = ocr_to_lines(result)
for i, (text, conf) in enumerate(lines[:12]):
    print(f"Line {i}: '{text}' | conf: {conf:.2f}")